In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

/kaggle/input/bangalore-house-prediction-processed-dataset/bangalore house price prediction cleaned.csv


In [2]:
df = pd.read_csv('/kaggle/input/bangalore-house-prediction-processed-dataset/bangalore house price prediction cleaned.csv')
df.head()

bath  balcony  price  total_sqft_int  bhk  price_per_sqft  \
0   3.0      2.0  150.0          1672.0    3     8971.291866   
1   3.0      3.0  149.0          1750.0    3     8514.285714   
2   3.0      2.0  150.0          1750.0    3     8571.428571   
3   2.0      2.0   40.0          1250.0    2     3200.000000   
4   2.0      2.0   83.0          1200.0    2     6916.666667   

   area_typeSuper built-up  Area  area_typeBuilt-up  Area  \
0                              1                        0   
1                              0                        1   
2                              1                        0   
3                              1                        0   
4                              0                        0   

   area_typePlot  Area  availability_Ready To Move  ...  \
0                    0                           1  ...   
1                    0                           1  ...   
2                    0                           1  ...   
3                    0                           1  ...   
4                    1                           1  ...   

   location_Kalena Agrahara  location_Horamavu Agara  location_Vidyaranyapura  \
0                         0                        0                        0   
1                         0                        0                        0   
2                         0                        0                        0   
3                         0                        0                        0   
4                         0                        0                        0   

   location_BTM 2nd Stage  location_Hebbal Kempapura  location_Hosur Road  \
0                       0                          0                    0   
1                       0                          0                    0   
2                       0                          0                    0   
3                       0                          0                    0   
4                       0                          0                    0   

   location_Horamavu Banaswadi  location_Domlur  location_Mahadevpura  \
0                            0                0                     0   
1                            0                0                     0   
2                            0                0                     0   
3                            0                0                     0   
4                            0                0                     0   

   location_Tumkur Road  
0                     0  
1                     0  
2                     0  
3                     0  
4                     0  

[5 rows x 108 columns]

In [3]:
X = df.drop('price', axis=1)
y = df['price']

print('Shape of X =', X.shape)
print('Shape of y =', y.shape)

Shape of X = (7120, 107)
Shape of y = (7120,)


In [4]:
X_train , X_test , y_train , y_test = train_test_split(X , y, test_size=0.2 , random_state=51)
print('Shape of X_train =', X.shape)
print('Shape of y_train =', y.shape)
print('Shape of X_test =', X.shape)
print('Shape of y_test =', y.shape)

Shape of X_train = (7120, 107)
Shape of y_train = (7120,)
Shape of X_test = (7120, 107)
Shape of y_test = (7120,)


In [5]:
sc = StandardScaler()
sc.fit(X_train)
X_train = sc.transform(X_train)
X_test = sc.transform(X_test)

In [6]:
lr = LinearRegression()
lr.fit(X_train,y_train)

LinearRegression()

In [7]:
lr.intercept_

95.0802729985955

In [8]:
X_test[0, :]

array([ 0.71301986,  0.0112734 ,  0.30202307,  0.65677518, -0.48064341,
       -1.7385623 ,  2.11587407, -0.25430867,  0.51007548, -0.18373025,
       -0.16389438, -0.1473229 , -0.13023539, -0.12812824, -0.12598816,
       -0.12454231, -0.12953656, -0.12381344, -0.12010681, -0.11551113,
       -0.10992018, -0.10909925, -0.10660036, -0.11234866, -0.09315135,
       -0.08618799, -0.08923672, -0.09023078, -0.08721571, -0.09023078,
       -0.08721571, -0.08195215, -0.08195215, -0.07633675, -0.0751646 ,
       -0.08085949, -0.0739743 , -0.07975227, -0.07153563, -0.0751646 ,
       -0.0677166 , -0.08085949, -0.07153563, -0.07862985, -0.0751646 ,
       -0.07862985, -0.06504853, -0.0751646 , -0.06901264, -0.0751646 ,
       -0.06901264, -0.07028523, -0.07276497, -0.07028523, -0.06367332,
       -0.06226825, -0.06226825, -0.06639573, -0.06504853, -0.05935999,
       -0.06083125, -0.06639573, -0.06639573, -0.06226825, -0.06367332,
       -0.05935999, -0.06639573, -0.06367332, -0.06226825, -0.06

In [9]:
lr.predict([X_test[0, :]])

array([76.90661876])

In [10]:
lr.predict(X_test)

array([ 76.90661876,  15.25005377, 113.6828165 , ...,  21.30296864,
        71.43462962, 230.0414626 ])

In [11]:
y_test

2435     80.00
3113     40.00
426     120.00
1124     79.00
1161     45.00
         ...  
2078     28.34
6855     84.00
4381     32.00
3862     63.00
43      180.00
Name: price, Length: 1424, dtype: float64

In [12]:
lr.score(X_test,y_test)

0.7903837092682255

In [13]:
from sklearn.linear_model import Ridge, Lasso

In [14]:
rd = Ridge()

rd.fit(X_train,y_train)
rd.score(X_test,y_test)

0.7905686374336628

In [15]:
ls = Lasso()

ls.fit(X_train,y_train)
ls.score(X_test,y_test)

0.8036373003525774

In [16]:
rd2 = Ridge(alpha=2)

rd2.fit(X_train,y_train)
rd2.score(X_test,y_test)

0.7907530260397942

In [17]:
ls2 = Lasso(alpha=2)

ls2.fit(X_train,y_train)
ls2.score(X_test,y_test)

0.8160181533703601

In [18]:
y_pred = lr.predict(X_test)
y_pred

array([ 76.90661876,  15.25005377, 113.6828165 , ...,  21.30296864,
        71.43462962, 230.0414626 ])

In [19]:
y_test

2435     80.00
3113     40.00
426     120.00
1124     79.00
1161     45.00
         ...  
2078     28.34
6855     84.00
4381     32.00
3862     63.00
43      180.00
Name: price, Length: 1424, dtype: float64

In [20]:
from sklearn.metrics import mean_squared_error

In [21]:
mse = mean_squared_error(y_test,y_pred)
rmse = np.sqrt(mse)
print('MSE = ' , mse)
print('RMSE = ' ,rmse)

MSE =  4211.806905823323
RMSE =  64.89843531105602


In [22]:
from sklearn.metrics import r2_score

In [23]:
r2_score(y_test,y_pred)

0.7903837092682255

In [24]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

In [25]:
poly_reg = PolynomialFeatures(degree=2)
poly_reg.fit(X_train)
X_train_poly = poly_reg.transform(X_train)
X_test_poly = poly_reg.transform(X_test)

In [26]:
X_train_poly.shape , X_test_poly.shape

((5696, 5886), (1424, 5886))

In [27]:
lr =LinearRegression()
lr.fit(X_train_poly,y_train)

LinearRegression()

In [28]:
lr.score(X_test_poly,y_test)

0.999768426975014

In [29]:
lr.predict([X_test_poly[0,:]])

array([80.])

In [30]:
y_pred1=lr.predict(X_test_poly)
y_pred1

array([ 80.,  40., 120., ...,  32.,  63., 180.])

In [31]:
y_test

2435     80.00
3113     40.00
426     120.00
1124     79.00
1161     45.00
         ...  
2078     28.34
6855     84.00
4381     32.00
3862     63.00
43      180.00
Name: price, Length: 1424, dtype: float64

In [32]:
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test,y_pred)
rmse = np.sqrt(mse)
mse,rmse

(4211.806905823323, 64.89843531105602)